### ISSUE TITLE
New process to publish to deno.land/x registry

### ISSUE THREAD

**Issue by sisou** [JohanWinther/websocket-server#13]
On August 3rd, 2020, Deno changed their procedure to publish packages on deno.land/x:
https://deno.com/blog/registry2

In short, you need to add a webhook to this repository. Please go to https://deno.land/x and scroll to below the initial list of packages. There, click the "Add a module" button, it will guide you.

Afterwards you might need to publish a tag `1.0.1` for it to register, or republish (or repush, is that possible?) the `1.0.0` tag.

Thanks!

**Comment by JohanWinther** [comment]
I have added a version 1.0.1, but also accidentally added the tag "1". Please ignore that and use 1.0.1.
